[최지수] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/32-westagram-backend-1-team pull request #11
Opened 2022-04-15 11:35 UTC by CHEESECHOUX

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- views.py urls.py 기본 코드 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- try & except와 if문의 차이는 무엇인가요?? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-16 10:13 UTC, Kang-kyunghun requested changes

2022-04-16 10:13 UTC, Kang-kyunghun commented on students/jisoo/westagram/users/urls.py
> +    path('signup/', SignupView.as_view()),
```suggestion
    path('/signup', SignupView.as_view()),
```

2022-04-16 10:13 UTC, Kang-kyunghun commented on students/jisoo/westagram/users/views.py
>  from django.views import View
```suggestion
from django.http  import JsonResponse
from django.views import View
```
import 기준으로 정렬해 주세요.

2022-04-16 10:13 UTC, Kang-kyunghun commented on students/jisoo/westagram/users/views.py
> +        try:
단순 create까지 잘 구현했습니다.
이제 이메일과 비밀번호 조건을 하나씩 추가해 보세요.

2022-04-17 10:55 UTC, CHEESECHOUX commented
수정했습니다!

2022-04-18 01:52 UTC, Kang-kyunghun requested changes

2022-04-18 01:52 UTC, Kang-kyunghun commented on students/jisoo/westagram/users/views.py
> +
불필요한 공백 제거해주세요.

2022-04-18 01:52 UTC, Kang-kyunghun commented on students/jisoo/westagram/users/views.py
> +                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 400)
```suggestion
            if not re.match(email_regex, data['email']):
                return JsonResponse({'message' : 'INVALID_EMAIL'}, status = 400)
            
            if not re.match(password_regex, data['password']):
                return JsonResponse({'message' : 'INVALID_PASSWORD'}, status = 400)
```
if 문들끼리에는 공백 한 칸을 추가해 주세요.

2022-04-18 01:53 UTC, Kang-kyunghun commented
아주 마이너한 수정 사항 리뷰 드렸습니다.
이것만 수정 되면 merge 하겠습니다.

2022-04-18 04:02 UTC, CHEESECHOUX commented
수정했습니다아!

2022-04-18 05:02 UTC, Kang-kyunghun commented
LGTM~!

2022-04-18 05:02 UTC, merged