[윤진섭] Mission 3 : 회원가입 기능 구현
wecode-bootcamp-korea/32-westagram-backend-1-team pull request #12
Opened 2022-04-15 15:19 UTC by nathanyoon1212

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-16 10:11 UTC, Kang-kyunghun requested changes

2022-04-16 10:11 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/urls.py
> +    path('', SignUpView.as_view()),
```suggestion
    path('/signup', SignUpView.as_view()),
```

2022-04-16 10:11 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +            data           = json.loads(request.body)
```suggestion
            data = json.loads(request.body)
```

2022-04-16 10:11 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
```suggestion
            return JsonResponse({'message':'created'}, status = 201)
        except KeyError:
            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
```
불필요한 공백입니다.

2022-04-16 10:11 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +                return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
```suggestion
            if not re.match(r"^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", data["email"]):
                return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
```
None이 False로 인식 되기 때문에 다음과 같이 수정하는 것이 좋습니다.

2022-04-16 10:11 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +                return JsonResponse({'message': 'INVALID_PASSWORD'}, status=400)
```suggestion
            if not re.match(r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$", data["password"]):
                return JsonResponse({'message': 'INVALID_PASSWORD'}, status=400)
```

2022-04-16 10:15 UTC, Kang-kyunghun commented
등록하려는 이메일이 존재하는지 판단하는 로직도 추가해 주세요.

2022-04-18 01:54 UTC, nathanyoon1212 commented
views.py와 urls.py 수정하였습니다.

2022-04-18 02:00 UTC, Kang-kyunghun requested changes

2022-04-18 02:00 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +from users.models import User
```suggestion
import json, re # 파이썬 built-in package

from django.http  import JsonResponse # third-party package
from django.views import View

from users.models import User #직적 만든 package
```

2022-04-18 02:00 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/urls.py
> +    path('', SignUpView.as_view()),
해당 엔드포인트는 제거해 주세요.

2022-04-18 02:00 UTC, Kang-kyunghun commented on students/jinsup/westagram/users/views.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
```suggestion
class SignUpView(View):
    def post(self, request):
        try:
            data = json.loads(request.body)
        
            username   = data['username']
            first_name = data['first_name']
            last_name  = data['last_name']
            email      = data['email']
            password   = data['password']
            number     = data['number']
        
            if not re.match(r"^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", data["email"]):
                return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)
  
            if not re.match(r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$", data["password"]):
                return JsonResponse({'message': 'INVALID_PASSWORD'}, status=400)
            
            if User.objects.filter(email = email).exists():
                return JsonResponse({'message' : 'Email_Already_Exists'}, status=400)
            
            User.objects.create(
                username   = username,
                first_name = first_name,
                last_name  = last_name,
                email      = email,
                password   = password,
                number     = number,
            )
            return JsonResponse({'message':'created'}, status = 201)
        except KeyError:
            return JsonResponse({'message' : 'KEY_ERROR'}, status = 400)
```
1. try의 위치를 한 번 더 생각해 보시면 좋을 것 같습니다. try이로 key error를 잡고 있는데, 진섭님께서 잡으신 try 범위 밖에서도 key error가 발생 할 수 있는 곳이 있습니다.
2. 이미 존재하는 user 판단하는 로직 잘 추가 하셨습니다. 다만 판단하는 순서만 조정하면 좋을 것 같습니다. 이미 존재하는 user에 대한 판단은 DB와의 통신이 필요하므로 그 전에 파이썬 자체에서 판단하는 로직을 처리를 한 후에 user 존재 여부를 판단하는 것이 더 좋을 것 같습니다.
3. 공백을 줄 때는 1칸만 주셔도 괜찮습니다.

2022-04-18 04:23 UTC, nathanyoon1212 commented
멘토님!
말씀하신 대로 다시 수정을 하였습니다.

2022-04-18 05:02 UTC, Kang-kyunghun commented
LGTM~!!

2022-04-18 05:19 UTC, merged